### ISSUE TITLE
How to calculate the coverage metric?

### ISSUE THREAD

**Issue by zhaoshitian** [bronyayang/HallE_Control#1]
How to calculate the coverage metric?

**Comment by bronyayang** [comment]
We added the coverage in cceval.py. Please pin me if any issue with the metric calculation, thanks!

**Comment by zhaoshitian** [comment]
> We added the coverage in cceval.py. Please pin me if any issue with the metric calculation, thanks!

I run the updated code, but there are some errors: "AttributeError: 'CHAIR' object has no attribute 'get_uncover_gpt4'".
It seems you don't implement this attribute in the cceval.py file.

**Comment by bronyayang** [comment]
> > We added the coverage in cceval.py. Please pin me if any issue with the metric calculation, thanks!
> 
> I run the updated code, but there are some errors: "AttributeError: 'CHAIR' object has no attribute 'get_uncover_gpt4'". It seems you don't implement this attribute in the cceval.py file.

I think it should be good now. Thanks for letting me know any issue of this file, we cannot run this since we are lost access to OpenAI keys now...

**Comment by zhaoshitian** [comment]
> > > We added the coverage in cceval.py. Please pin me if any issue with the metric calculation, thanks!
> > 
> > 
> > I run the updated code, but there are some errors: "AttributeError: 'CHAIR' object has no attribute 'get_uncover_gpt4'". It seems you don't implement this attribute in the cceval.py file.
> 
> I think it should be good now. Thanks for letting me know any issue of this file, we cannot run this since we are lost access to OpenAI keys now...

Now I can run the code. Thank you for your effort!
